plugin:
  name: custom-data-type-zotero
  version: 0.1
  url: https://github.com/ssciwr/easydb-zotero-datatype-plugin
  displayname:
    de-DE: Zotero Bibliographie Plugin
    en-US: Zotero bibliography Plugin
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-zotero.js
    l10n: l10n/

base_config:
  - name: zotero
    group: zotero
    parameters:
      apikey:
        type: text
        position: 0
  - name: update_interval_zotero
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 1
        position: 0

custom_types:
  zotero:
    update:
      script: build/updater/zotero-update.js
      interval_base_config: update_interval_zotero.days
      timeout: 10
      batch_size: 100
